#!/bin/sh -ex

install_libpcap() {
    install_prefix=${1:?'install_prefix required'}
    mkdir libpcap
    wget -qO - https://github.com/the-tcpdump-group/libpcap/archive/libpcap-1.9.1.tar.gz |
        tar -xzf - -C libpcap --strip-components 1
    cmake -D CMAKE_INSTALL_PREFIX="$install_prefix" -D ENABLE_REMOTE=OFF \
        -G Ninja -S libpcap -B libpcap/build
    ninja -C libpcap/build
    $sudo ninja -C libpcap/build install
    rm -r libpcap
}

pacman -S --needed --noconfirm \
       bison flex make \
       mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc \
       mingw-w64-x86_64-libmaxminddb mingw-w64-x86_64-ninja \
       mingw-w64-x86_64-openssl python-pip zip

install_libpcap /mingw64

