#!/bin/sh -ex


export PATH=/mingw64/bin:$PATH

choco install winpcap --no-progress

curl -o npcap-sdk-1.01.zip https://nmap.org/npcap/dist/npcap-sdk-1.01.zip
7z x -y -o'c:\npcap\' npcap-sdk-1.01.zip


pacman -Su --noconfirm libyaml-devel pcre-devel jansson-devel
pacman -Su --noconfirm \
       mingw-w64-x86_64-libyaml mingw-w64-x86_64-pcre mingw-w64-x86_64-ninja \
       mingw-w64-x86_64-rust mingw-w64-x86_64-jansson mingw-w64-x86_64-nss mingw-w64-x86_64-nspr



git clone --depth 1 --branch brim-suricata-5.0.3 https://github.com/brimsec/suricata.git
cd suricata
git clone https://github.com/OISF/libhtp -b 0.5.x
dos2unix.exe libhtp/configure.ac
dos2unix.exe libhtp/htp.pc.in
dos2unix.exe libhtp/Makefile.am
./autogen.sh

# hack to make configure mis-detect -DFORTIFY_SOURCE as being unavailable.
sed -i 's/FORTIFY_SOURCE/FORTIFY_SOURCE_DISABLE/g' ./configure
sed -i 's/FORTIFY_SOURCE/FORTIFY_SOURCE_DISABLE/g' ./libhtp/configure

cd suricata-update
curl -L \
     https://github.com/OISF/suricata-update/archive/master.tar.gz | \
    tar zxvf - --strip-components=1
cd ..


./configure --with-libpcap-libraries=/c/npcap/Lib/x64 --with-libpcap-includes=/c/npcap/Include --disable-shared --disable-rust
make -j2

