#!/usr/bin/env bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

if [ -z "$BRIM_SURICATA_USER_DIR" ]; then
    datadir="$dir/var/lib/suricata"
else
    datadir="$BRIM_SURICATA_USER_DIR"
    if [ ! -d "$datadir" ]; then
        mkdir -p "$datadir"
    fi
fi


echo "
data-directory: $datadir
dist-rule-directory: $dir/share/suricata/rules
" > $datadir/update.yaml

exec "$dir/bin/suricata-update" --suricata "$dir/bin/suricata" --suricata-conf "$dir/brim-conf.yaml" --conf $dir/update.yaml --no-test --no-reload
