name: macOS build

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*brim*

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        brew install rust pkg-config
        brew install jansson libmagic libnet libyaml lz4 nspr nss pcre bzip2
        brew install autoconf automake libtool
        pip3 install pyyaml pyinstaller==4.5.1
    - name: clone Suricata and autogen
      run: |
        git clone --depth 1 --branch brim-suricata-5.0.3 https://github.com/brimdata/suricata.git
        cd suricata
        git clone https://github.com/OISF/libhtp -b 0.5.x
        ./autogen.sh
    - name: get suricata-update
      run: |
        curl -L \
              https://github.com/brimdata/suricata-update/archive/master.tar.gz | \
              tar zxvf - --strip-components=1
      working-directory: suricata/suricata-update
    - name: configure and build
      run: cd suricata && ./configure --disable-gccmarch-native  --disable-shared --enable-static --prefix=$HOME/suricata && make -j2
    - name: build static binary
      run: |
        cp Makefile-macOS.brim suricata/src/Makefile.brim
        cd suricata/src
        # remove the dynamically-linked suricata and re-link statically using our Makefile
        rm suricata
        make -f Makefile.brim
        cd ..
        make install-full
        chmod og+r $HOME/suricata/etc/suricata/*
      env:
        PYTHONPATH: /Users/runner/suricata/lib/python3.9/site-packages
    - name: add and fix dylibs
      run: |
        cd $HOME/suricata/bin

        nss_version=$(brew list --versions nss | cut -d ' ' -f 2)
        nspr_version=$(brew list --versions nspr | cut -d ' ' -f 2)

        cp /usr/local/lib/libfreebl3.dylib .
        cp /usr/local/lib/libsoftokn3.dylib .
        cp /usr/local/lib/libnssutil3.dylib .
        cp /usr/local/opt/nspr/lib/libnspr4.dylib .
        cp /usr/local/opt/nspr/lib/libplds4.dylib .
        cp /usr/local/opt/nspr/lib/libplc4.dylib .

        chmod +w *.dylib

        install_name_tool libsoftokn3.dylib -change /usr/local/Cellar/nss/"$nss_version"/lib/libnssutil3.dylib @executable_path/libnssutil3.dylib
        install_name_tool libsoftokn3.dylib -change /usr/local/opt/nspr/lib/libplc4.dylib @executable_path/libplc4.dylib
        install_name_tool libsoftokn3.dylib -change /usr/local/opt/nspr/lib/libplds4.dylib @executable_path/libplds4.dylib
        install_name_tool libsoftokn3.dylib -change /usr/local/opt/nspr/lib/libnspr4.dylib @executable_path/libnspr4.dylib

        install_name_tool libnssutil3.dylib -change /usr/local/opt/nspr/lib/libplc4.dylib @executable_path/libplc4.dylib
        install_name_tool libnssutil3.dylib -change /usr/local/opt/nspr/lib/libplds4.dylib @executable_path/libplds4.dylib
        install_name_tool libnssutil3.dylib -change /usr/local/opt/nspr/lib/libnspr4.dylib @executable_path/libnspr4.dylib

        install_name_tool libfreebl3.dylib -change /usr/local/opt/nspr/lib/libnspr4.dylib @executable_path/libnspr4.dylib
        install_name_tool libfreebl3.dylib -change /usr/local/Cellar/nss/"$nss_version"/lib/libnssutil3.dylib @executable_path/libnssutil3.dylib

        install_name_tool libplds4.dylib -change /usr/local/Cellar/nspr/"$nspr_version"/lib/libnspr4.dylib @executable_path/libnspr4.dylib

        install_name_tool libplc4.dylib -change /usr/local/Cellar/nspr/"$nspr_version"/lib/libnspr4.dylib @executable_path/libnspr4.dylib
    - name: freeze suricata-update
      run: |
        pyinstaller --onefile bin/suricata-update
        cp dist/suricata-update $HOME/suricata/bin
      working-directory: suricata/suricata-update
    - name: add brim files
      run: |
        cp brim-conf.yaml $HOME/suricata
        cp suricataupdater $HOME/suricata
        cp suricatarunner-macOS $HOME/suricata/suricatarunner
    - name: add magic file
      run: |
        version=$(brew list --versions libmagic | cut -d ' ' -f 2)
        echo found libmagic version $version
        mkdir -p $HOME/suricata/share/file
        cp /usr/local/Cellar/libmagic/$version/share/misc/magic.mgc $HOME/suricata/share/file
    - name: prune unneeded installed files
      run: |
        rm -rf $HOME/suricata/share/doc
        rm -rf $HOME/suricata/lib
        rm -rf $HOME/suricata/include
    - name: create zip
      run: |
        label=$(git describe --always --tags)
        pushd $HOME && zip -r suricata-$label.$(go env GOOS)-$(go env GOARCH).zip suricata
        popd && mv $HOME/suricata*zip .
    - uses: actions/upload-artifact@v2
      with:
        name: macos
        path: suricata-*.zip
    - if: startsWith(github.event.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@1.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: suricata-*.zip
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
