name: Python debug

on:
  pull_request:
  push:
    branches:
      - master

defaults:
 run:
   shell: bash

jobs:
  build:

    runs-on: windows-2019
    steps:
    - name: Use MSYS2's bash.exe in subsequent steps.
      run: echo "C:\msys64\usr\bin" >> $GITHUB_PATH
    - uses: actions/checkout@v2
    - name: Setup Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_CREDENTIAL_BRIMSEC_BUCKET }}
    - name: install deps
      run: |
        uname -a
        choco install winpcap --no-progress
        curl -o npcap-sdk-1.01.zip https://nmap.org/npcap/dist/npcap-sdk-1.01.zip
        7z x -y -o'c:\npcap\' npcap-sdk-1.01.zip
        pacman -Su --noconfirm libyaml-devel pcre-devel jansson-devel
        pacman -Su --noconfirm \
          mingw-w64-x86_64-libyaml mingw-w64-x86_64-pcre mingw-w64-x86_64-ninja \
          mingw-w64-x86_64-rust mingw-w64-x86_64-jansson mingw-w64-x86_64-nss mingw-w64-x86_64-nspr
        pacman -Su --noconfirm python3-pip
        pip3 install --upgrade pip
        pip3 install pyyaml
        pip3 list
        which pip3
        which python
        python --version
    - name: try import yaml
      run:  python -c "import yaml"
    - name: Add mingw64 bin path
      run: echo "/mingw64/bin" >> $GITHUB_PATH
    - name: try import yaml
      run:  python -c "import yaml"
    - name: configure and build Suricata
      run: |
        pip3 install --upgrade pip
        pip3 install pyyaml
        pip3 list
        uname -a
        CFLAGS=-DPCRE_STATIC= ./configure --with-libpcap-libraries=/c/npcap/Lib/x64 --with-libpcap-includes=/c/npcap/Include --disable-shared --enable-static --prefix $HOME/suricata
        make -j2
        cp ../Makefile-windows.brim src/Makefile.brim
        cd src
        # re-link with some our modified Makefile that statically links those static libs that could be.
        rm suricata && make -f Makefile.brim
        cd ..
        make install
        # make install-conf doesn't work on windows as it has hard-coded to write to C:/Program Files/suricata.
        mkdir -p $HOME/suricata/etc/suricata && cp suricata.yaml threshold.config etc/{classification,reference}.config $HOME/suricata/etc/suricata
        # add the .dlls that couldn't be statically linked.
        mkdir $HOME/suricata/dlls && cp /mingw64/bin/{libnspr4.dll,libplc4.dll,libplds4.dll,libwinpthread-1.dll,nss3.dll,nssutil3.dll} $HOME/suricata/dlls
        # make install-rules doesn't work on github actions windows runner because configure doesn't detect the presence of python.
        cd src &&  make -f Makefile.brim install-rules
      working-directory: suricata
