name: Suricata-for-Brim Ubuntu build

on:
  pull_request:
  # push:
  #   branches:
  #     - build-ubuntu*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_CREDENTIAL_BRIMSEC_BUCKET }}
    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get -y install libpcre3 libpcre3-dev build-essential autoconf \
        automake libtool libpcap-dev libnet1-dev libyaml-0-2 libyaml-dev zlib1g zlib1g-dev \
        libcap-ng-dev libcap-ng0 make libmagic-dev libjansson-dev libjansson4 pkg-config libnss3-dev \
        libnspr4-dev liblz4-dev zip
    - name: download suricata sources
      run: |
        curl -o suricata-5.0.3.tar.gz https://www.openinfosecfoundation.org/download/suricata-5.0.3.tar.gz
        tar xvzf suricata-5.0.3.tar.gz
    - name: configure and build
      run: cd suricata-5.0.3 && ./configure --enable-static=yes --enable-shared=no --prefix=$HOME/suricata && make -j2 && make install-full
    - name: add brim files
      run: cp suricatarunner brim-conf.yaml $HOME/suricata
    - name: create zip
      run: cd $HOME && zip -r suricata-v5.0.3-brim3.linux-amd64.zip suricata
    - name: Upload release artifacts to Google Cloud Storage bucket
      run: |
        gsutil cp $HOME/suricata-v5.0.3-brim3.linux-amd64.zip gs://brimsec/suricata/

