name: Ubuntu build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_CREDENTIAL_BRIMSEC_BUCKET }}
    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get -y install libpcre3 libpcre3-dev build-essential autoconf \
        automake libtool ninja-build libnet1-dev libyaml-0-2 libyaml-dev zlib1g zlib1g-dev \
         libcap-ng-dev libcap-ng0 make libmagic-dev libjansson-dev libjansson4 pkg-config libnss3-dev \
        libnspr4-dev liblz4-dev zip rustc cargo python3-setuptools
        pip3 install wheel
        pip3 install pyinstaller
    - name: build libpcap
      run: |
        ./build-libpcap
    - name: clone Suricata and autogen
      run: |
        git clone --depth 1 --branch brim-suricata-5.0.3 https://github.com/brimsec/suricata.git
        cd suricata
        git clone https://github.com/OISF/libhtp -b 0.5.x
        ./autogen.sh
    - name: get suricata-update
      run: |
        curl -L \
              https://github.com/brimsec/suricata-update/archive/master.tar.gz | \
              tar zxvf - --strip-components=1
      working-directory: suricata/suricata-update
    - name: configure and build
      # --disable-gccmatch-native is to avoid "illegal instruction" crashes when running on a different x86_64 CPU.
      run: cd suricata && ./configure --disable-gccmarch-native  --disable-shared --enable-static --prefix=$HOME/suricata && make -j2
    - name: build static binary
      run: |
        cp Makefile-linux.brim suricata/src/Makefile.brim
        cd suricata/src
        # remove the dynamically-linked suricata and re-link statically using our Makefile
        rm suricata
        make -f Makefile.brim suricata
        cd ..
        make install-full
    - name: freeze suricata-update
      run: |
        ~/.local/bin/pyinstaller --onefile bin/suricata-update
        cp dist/suricata-update $HOME/suricata/bin
      working-directory: suricata/suricata-update
    - name: add brim files
      run: |
        cp brim-conf.yaml $HOME/suricata
        cp suricataupdater $HOME/suricata
        cp suricatarunner-linux $HOME/suricata/suricatarunner
    - name: create zip
      run: cd $HOME && zip -r suricata-v5.0.3-brim16.$(go env GOOS)-$(go env GOARCH).zip suricata
    - if: github.ref == 'refs/heads/master'
      name: Upload release artifacts to Google Cloud Storage bucket
      run: |
        gsutil cp $HOME/suricata-v5.0.3-brim16.linux-amd64.zip gs://brimsec/suricata/
