name: Suricata-for-Brim Ubuntu build

on:
  pull_request:
  # push:
  #   branches:
  #     - build-ubuntu*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo apt-get -y install libpcre3 libpcre3-dbg libpcre3-dev build-essential autoconf \
        automake libtool libpcap-dev libnet1-dev libyaml-0-2 libyaml-dev zlib1g zlib1g-dev \
        libcap-ng-dev libcap-ng0 make libmagic-dev libjansson-dev libjansson4 pkg-config libnss3-dev \
        libnspr4-dev liblz4-dev
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'
