name: Ubuntu build

on:
  pull_request:
  push:
    branches:
      - current-actions-runners
    tags:
      - v*brim*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get -y install libpcre3 libpcre3-dev build-essential autoconf \
        automake libtool ninja-build libnet1-dev libyaml-0-2 libyaml-dev zlib1g zlib1g-dev \
         libcap-ng-dev libcap-ng0 make libmagic-dev libjansson-dev libjansson4 pkg-config libnss3-dev \
        libnspr4-dev liblz4-dev zip rustc cargo python3-setuptools
        pip3 install wheel
        pip3 install pyinstaller==4.5.1
    - name: build libpcap
      run: |
        ./build-libpcap
    - name: clone Suricata and autogen
      run: |
        git clone --depth 1 --branch brim-suricata-5.0.3 https://github.com/brimdata/suricata.git
        cd suricata
        git clone https://github.com/OISF/libhtp -b 0.5.x
        ./autogen.sh
    - name: get suricata-update
      run: |
        curl -L \
              https://github.com/brimdata/suricata-update/archive/master.tar.gz | \
              tar zxvf - --strip-components=1
      working-directory: suricata/suricata-update
    - name: configure and build
      # --disable-gccmatch-native is to avoid "illegal instruction" crashes when running on a different x86_64 CPU.
      run: cd suricata && ./configure --disable-gccmarch-native  --disable-shared --enable-static --prefix=$HOME/suricata && make -j2
    - name: build static binary
      run: |
        cp Makefile-linux.brim suricata/src/Makefile.brim
        cd suricata/src
        # remove the dynamically-linked suricata and re-link statically using our Makefile
        rm suricata
        make -f Makefile.brim suricata
        cd ..
        make install-full
        chmod og+r $HOME/suricata/etc/suricata/*
    - name: add dynamic libraries
      run: |
        cd $HOME/suricata/bin
        cp /usr/lib/x86_64-linux-gnu/libnss3.so .
        cp /usr/lib/x86_64-linux-gnu/libnspr4.so .
        cp /usr/lib/x86_64-linux-gnu/libnssutil3.so .
        cp /usr/lib/x86_64-linux-gnu/libplds4.so .
        cp /usr/lib/x86_64-linux-gnu/libplc4.so .
        cp /usr/lib/x86_64-linux-gnu/libfreebl3.so .
        cp /usr/lib/x86_64-linux-gnu/libfreeblpriv3.so .
        cp /usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so .
    - name: freeze suricata-update
      run: |
        ~/.local/bin/pyinstaller --onefile bin/suricata-update
        cp dist/suricata-update $HOME/suricata/bin
      working-directory: suricata/suricata-update
    - name: add brim files
      run: |
        cp brim-conf.yaml $HOME/suricata
        cp suricataupdater $HOME/suricata
        cp suricatarunner-linux $HOME/suricata/suricatarunner
    - name: add magic file
      run: |
        mkdir -p $HOME/suricata/share/file
        cp /usr/lib/file/magic.mgc $HOME/suricata/share/file
    - name: prune unneeded installed files
      run: |
        rm -rf $HOME/suricata/share/doc
        rm -rf $HOME/suricata/lib
        rm -rf $HOME/suricata/include
    - name: create zip
      run: |
        label=$(git describe --always --tags)
        pushd $HOME && zip -r suricata-$label.$(go env GOOS)-$(go env GOARCH).zip suricata
        popd && mv $HOME/suricata*zip .
    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu
        path: suricata-*.zip
    - if: startsWith(github.event.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@1.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: suricata-*.zip
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
