name: Windows build

on:
  pull_request:
  push:
    branches:
      - master

defaults:
 run:
   shell: bash

jobs:
  build:

    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Use MSYS2's bash.exe in subsequent steps.
      run: echo 'C:\msys64\usr\bin' >> $GITHUB_PATH
    - name: Add mingw64 bin path
      run: echo "/mingw64/bin" >> $GITHUB_PATH
    - name: Setup Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_CREDENTIAL_BRIMSEC_BUCKET }}
    - name: install deps
      run: |
        pacman -Su --noconfirm libyaml-devel pcre-devel jansson-devel
        pacman -Su --noconfirm \
          mingw-w64-x86_64-libyaml mingw-w64-x86_64-pcre mingw-w64-x86_64-ninja \
          mingw-w64-x86_64-rust mingw-w64-x86_64-jansson mingw-w64-x86_64-nss mingw-w64-x86_64-nspr

    - name: build libpcap
      run: |
        pacman -S --needed --noconfirm bison flex mingw-w64-x86_64-cmake
        ./build-libpcap
    - name: clone Suricata and autogen
      run: |
        git clone --depth 1 --branch brim-suricata-5.0.3 https://github.com/brimsec/suricata.git
        cd suricata
        git clone https://github.com/OISF/libhtp -b 0.5.x
        dos2unix.exe libhtp/configure.ac
        dos2unix.exe libhtp/htp.pc.in
        dos2unix.exe libhtp/Makefile.am
        ./autogen.sh
    - name: configure and build
      run: |
        CFLAGS=-DPCRE_STATIC= ./configure --disable-gccmarch-native --disable-shared --enable-static --enable-gccprotect --prefix /home/runneradmin/suricata
        make -j2
        cp ../Makefile-windows.brim src/Makefile.brim
        cd src
        # re-link with some our modified Makefile that statically links those static libs that could be.
        rm suricata && make -f Makefile.brim
        cd ..
      working-directory: suricata
    - name: install
      run: |
        make install
        # make install-conf doesn't work on windows as it has hard-coded to write to C:/Program Files/suricata.
        mkdir -p /home/runneradmin/suricata/etc/suricata && cp suricata.yaml threshold.config etc/{classification,reference}.config /home/runneradmin/suricata/etc/suricata
        chmod og+r /home/runneradmin/suricata/etc/suricata/*
        # add the .dlls that couldn't be statically linked.
        mkdir /home/runneradmin/suricata/dlls
        cp /mingw64/bin/pcap.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/libnspr4.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/libplc4.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/libplds4.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/libssp-0.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/libwinpthread-1.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/nss3.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/nssutil3.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/zlib1.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/softokn3.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/freebl3.dll /home/runneradmin/suricata/dlls
        cp /mingw64/bin/libsqlite3-0.dll /home/runneradmin/suricata/dlls

        # We install rules this way rather than "make install-rules"
        # because (1) the configure script on the github actions windows
        # runner doesn't detect the presence of python yaml lib (though
        # it does on a regular win/msys) and (2) the suricata-update
        # python script fails with a certificate error when trying to connect
        # to https://rules.emergingthreats.net.
        pacman -Su --noconfirm python3-pip
        pip3 install --upgrade pip
        pip3 install pyyaml
        mkdir -p /home/runneradmin/suricata/var/lib/suricata
        pip3 install suricata-update
        suricata-update --suricata-version 5.0.3 --url https://rules.emergingthreats.net/open/suricata-5.0.3/emerging.rules.tar.gz \
          --local /home/runneradmin/suricata/share/suricata/rules --suricata-conf /home/runneradmin/suricata/etc/suricata/suricata.yaml \
          --data-dir /home/runneradmin/suricata/var/lib/suricata \
          --no-test --no-reload
      working-directory: suricata
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: build runner
      run: |
        go build -o suricatarunner.exe go/runner/main.go
        go build -o suricataupdater.exe go/updater/main.go
    - name: add brim files
      run: |
        cp brim-conf.yaml /home/runneradmin/suricata
        cp suricatarunner.exe suricataupdater.exe /home/runneradmin/suricata/
    - name: freeze suricata-update
      run: |
        curl -L https://github.com/brimsec/suricata-update/archive/fix-windows.tar.gz | tar zxvf - --strip-components=1
        pip3 install pyinstaller
        pyinstaller --onefile bin\suricata-update
        cp dist\suricata-update.exe C:\msys64\home\runneradmin\suricata\bin
      shell: cmd
    - name: create zip
      run: |
        cd /home/runneradmin && zip -r suricata-v5.0.3-brim20.$(go env GOOS)-$(go env GOARCH).zip suricata
    - if: github.ref == 'refs/heads/master'
      name: Upload release artifacts to Google Cloud Storage bucket
      run: |
        gsutil cp /home/runneradmin/suricata-v5.0.3-brim20.$(go env GOOS)-$(go env GOARCH).zip gs://brimsec/suricata/suricata-v5.0.3-brim20.$(go env GOOS)-$(go env GOARCH).zip
