name: Windows build

on:
  pull_request:
  push:
    branches:
      - master

defaults:
 run:
   shell: bash

jobs:
  build:

    runs-on: windows-2019
    steps:
    - name: Use MSYS2's bash.exe in subsequent steps.
      run: echo '::add-path::C:\msys64\usr\bin'
    - uses: actions/checkout@v2
    - name: Setup Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_CREDENTIAL_BRIMSEC_BUCKET }}
    - name: install deps
      run: |
        choco install winpcap --no-progress
        curl -o npcap-sdk-1.01.zip https://nmap.org/npcap/dist/npcap-sdk-1.01.zip
        7z x -y -o'c:\npcap\' npcap-sdk-1.01.zip
        pacman -Su --noconfirm libyaml-devel pcre-devel jansson-devel
        pacman -Su --noconfirm \
          mingw-w64-x86_64-libyaml mingw-w64-x86_64-pcre mingw-w64-x86_64-ninja \
          mingw-w64-x86_64-rust mingw-w64-x86_64-jansson mingw-w64-x86_64-nss mingw-w64-x86_64-nspr
    - name: clone Suricata and autogen
      run: |
        git clone --depth 1 --branch brim-suricata-5.0.3 https://github.com/brimsec/suricata.git
        cd suricata
        git clone https://github.com/OISF/libhtp -b 0.5.x
        dos2unix.exe libhtp/configure.ac
        dos2unix.exe libhtp/htp.pc.in
        dos2unix.exe libhtp/Makefile.am
        ./autogen.sh
        # hack to make configure mis-detect -DFORTIFY_SOURCE as being unavailable.
        sed -i 's/FORTIFY_SOURCE/FORTIFY_SOURCE_DISABLE/g' ./configure
        sed -i 's/FORTIFY_SOURCE/FORTIFY_SOURCE_DISABLE/g' ./libhtp/configure
    - name: get suricata-update
      run: |
        curl -L \
              https://github.com/OISF/suricata-update/archive/master.tar.gz | \
              tar zxvf - --strip-components=1
      working-directory: suricata/suricata-update
    - name: configure and build
      run: |
        ./configure --with-libpcap-libraries=/c/npcap/Lib/x64 --with-libpcap-includes=/c/npcap/Include --disable-shared --enable-static
        make -j2
      working-directory: suricata
